#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# PHP Debugger (xdebug|blackfire|none)

PHP_DEBUGGER=xdebug # none, xdebug, blackfire

#XDEBUG_MODE=develop,debug,trace
#XDEBUG_PROFILER_ENABLE=1
#XDEBUG_OUTPUT_DIR=/app/xdebug
php.xdebug.trace-output-name=trace-%R-%u
XDEBUG_TRACE_OUTPUT_NAME=trace-%R-%u

#####################
# Debug console apps
#####################

#XDEBUG_REMOTE_AUTOSTART=1
#XDEBUG_REMOTE_CONNECT_BACK=0
#XDEBUG_DISCOVER_CLIENT_HOST=0

# run make x and update this ip
XDEBUG_CLIENT_HOST=172.27.0.1

######################
# /Debug console apps
######################

PHP_DATE_TIMEZONE=Europe/Moscow

#######################################
# Context environment

# TYPO3
TYPO3_CONTEXT=Development/Docker

# Symfony
SYMFONY_ENV=dev
SYMFONY_DEBUG=0

# CakePHP
CAKE_ENV=dev

# yii
YII_ENVIRONMENT=Development

